services:
  dev-app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./src:/app/src
    platform: linux/x86_64
