services:
  dev-app:
    image: ${DOCKER_USERNAME}/dev-app:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: dev-app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./src:/app/src
    platform: linux/x86_64
    environment:
      # 환경변수 0. docker-compose
      - APP_PORT=${secrets.APP_PORT}
      - DOCKER_USERNAME=${secrets.DOCKER_USERNAME}
      # 앱에서 쓰는 환경변수 1. DB
      - INCLUDE_STACKTRACE=true
      - MYSQL_HOST=${secrets.MYSQL_HOST}
      - MYSQL_PORT=${secrets.MYSQL_PORT}
      - MYSQL_USERNAME=${secrets.MYSQL_USERNAME}
      - MYSQL_PASSWORD=${secrets.MYSQL_PASSWORD}
      - MYSQL_DATABASE=${secrets.MYSQL_DATABASE}
      # 앱에서 쓰는 환경변수 2. jwt
      - JWT_SECRET=${secrets.JWT_SECRET}
      - JWT_EXPIRES_IN=${secrets.JWT_EXPIRES_IN}
      - JWT_ISSUER=${secrets.JWT_ISSUER}
      - JWT_SUBJECT=${secrets.JWT_SUBJECT}
      # 앱에서 쓰는 환경변수 3. cloudflare
      - CLOUDFLARE_ACCOUNT_ID=${secrets.CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_API_TOKEN=${secrets.CLOUDFLARE_API_TOKEN}
