services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80' # 호스트의 80 포트를 컨테이너의 80 포트에 매핑 (HTTP) > caddy에서 Let's Encrypt 인증서 발급받을 때 필요, http > https로 리다이렉션 할 때도 필요
      - '443:443' # 호스트의 443 포트를 컨테이너의 443 포트에 매핑 (HTTPS)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # 현재 디렉터리의 Caddyfile을 컨테이너 내부 설정 파일로 연결
      - ./caddy_data:/data # SSL 인증서 등 Caddy 내부 데이터 저장 위치 (persistent volume)
      - ./caddy_config:/config # Caddy의 내부 설정 저장 위치 (persistent volume)
    extra_hosts:
      - 'host.docker.internal:host-gateway'
